[versions]
#accompanistGlide = "0.30.1"
accompanistSystemuicontroller = "0.34.0"
agp = "8.8.2"
#kotlin = "2.1.0"
#ksp = "2.0.0-1.0.21"
coilCompose = "2.7.0"
coilGif = "2.5.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.1.0"
kotlinxMetadataJvmVersion = "0.5.0"
ksp = "2.1.10-1.0.30"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
hilt = "2.55"
hiltAndroid = "2.55"
hiltNavigationCompose = "1.2.0"
kapt = "2.1.0"
compose = "1.8.0"
lifecycle = "2.8.7"
hilt-nav = "1.2.0"
playServicesAds = "24.7.0"
retrofit = "2.11.0"
okhttp = "5.0.0-alpha.1"
room = "2.7.1"
foundationAndroid = "1.8.0"
material3Android = "1.3.2"
#datastorePreferences = "1.1.5"
datastorePreferences = "1.1.0-alpha05"
firebaseBom = "33.13.0"
composeCompiler = "1.5.15"
serialization = "2.1.0"
crashlyticsVersion = "3.0.3"
sdpCompose = "1.1.0"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"
accompanistPager = "0.28.0"
lottieCompose = "6.5.2"
userMessagingPlatform = "3.2.0"
vico = "2.1.3"

[libraries]
#accompanist-glide = { module = "com.google.accompanist:accompanist-glide", version.ref = "accompanistGlide" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }

ads-sdk = { module = "com.github.developwithishfaq:mon-jetpack", version = "2.0-alpha01" }
#ads-compose = { group = "com.github.appsapiconsole", name = "tet-ads-compose", version = "0.0.13-beta04" }
ads-compose = { group = "com.github.appsapiconsole", name = "tet-ads-compose", version = "0.0.20-exp-04" }
remote-config = { group = "com.github.appsapiconsole", name = "tet-remote-config", version = "0.0.2" }
mon-consent = { group = "com.github.appsapiconsole", name = "tet-consent", version = "0.0.2" }
app-update = { group = "com.github.appsapiconsole", name = "tet-app-update", version = "0.0.1" }

#vico graph
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
user-messaging-platform = { module = "com.google.android.ump:user-messaging-platform", version.ref = "userMessagingPlatform" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }


#jetbrains-kotlinx-metadata-jvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvmVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
# Jetpack Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
sdp-compose = { module = "com.github.Kaaveh:sdp-compose", version.ref = "sdpCompose" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
# Retrofit & OkHttp
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

#Firebase
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

#LottieCompose
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsVersion" }
kotlin-serialization= { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
